FROM ubuntu:16.04
MAINTAINER Ponchau Simon <simon@ponchau.eu>

RUN apt-get update
RUN apt-get install -y apache2
RUN apt-get install -y php
RUN apt-get install -y php-mysql
RUN apt-get install -y nano

RUN service apache2 start

